@startuml
left to right direction

Merchant -> (Create \n an Offer)
Merchant --> (Cancel \nan Offer)


Customer -> (Retrieve active \n Merchant Offers)
Customer --> (Retrieve an \n active Merchant Offer)
@enduml
